#                    Copyright © 2016 , UChicago Argonne, LLC
#                              All Rights Reserved
#                               OPEN SOURCE LICENSE

# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimer.  Software changes, modifications, or
# derivative works, should be noted with comments and the author and organization’s name.

# 2. Redistributions in binary form must reproduce the above copyright notice, this list
# of conditions and the following disclaimer in the documentation and/or other materials
# provided with the distribution.

# 3. Neither the names of UChicago Argonne, LLC or the Department of Energy nor the names
# of its contributors may be used to endorse or promote products derived from this software
# without specific prior written permission.

# 4. The software and the end-user documentation included with the redistribution, if any,
# must include the following acknowledgment:

# "This product includes software produced by UChicago Argonne, LLC under Contract
# No. DE-AC02-06CH11357 with the Department of Energy.”

# ******************************************************************************************************
#                                             DISCLAIMER

# THE SOFTWARE IS SUPPLIED "AS IS" WITHOUT WARRANTY OF ANY KIND.

# NEITHER THE UNITED STATES GOVERNMENT, NOR THE UNITED STATES DEPARTMENT OF ENERGY, NOR UCHICAGO ARGONNE,
# LLC, NOR ANY OF THEIR EMPLOYEES, MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LEGAL LIABILITY
# OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, DATA, APPARATUS,
# PRODUCT, OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.

# ***************************************************************************************************

# 02-Apr-2017 by Ralph Muehleisen
# Created to remove inline R in Ruby code



#

#==============================================================%
#                        REQUIRED INPUTS                       %
#==============================================================%
#   y_file: a model response file with energy outputs to analyze
#   file_path: path to Morris_design file
# 	file_name: full path name to the UQ output generated by SA.rb
#===============================================================%
#                           OUTPUTS                             %
#===============================================================%
#  	CSV file with sensitivity
# 	plots of sensitivity results

#===============================================================%

computeSensitivities <- function(y_file, file_path, file_name)

	file_name = '../Install/SA_Output/UQ_test.csv'
	y_file = "../Install/SA_Output/Simulation_Results_Building_Total_Energy.csv"
	file_path = '../Install/SA_Output'

	library(sensitivity)
	
	table_name <- read.csv(file_name, header = TRUE, fill = TRUE, strip.white = TRUE, stringsAsFactors=TRUE)
	a = table_name[1]
	b = t(a)

	load("#{file_path}/Morris_design")
	Table <- read.csv(y_file,header=TRUE)
	Y <- data.matrix(Table)
	pdf(sprintf("%s/Sensitivity_Plots.pdf",file_path))
	for (i in 1:dim(Y)[2]){
		tell(design,Y[, i])
		write.csv(print(design), file = sprintf("%s/SA_wrt_%s.csv", file_path, names(Table)[i]),row.names = b)
		plot(design, main = names(Table)[i])
	}
	dev.off()

}
